FROM python:3.14-slim@sha256:cad9a2c871761c413caa6fdd6441c783451e740a48aaeba60ae62a8b53525ef6

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY publisher.py .
RUN pip install --no-cache-dir paho-mqtt structlog

CMD ["python", "publisher.py"]