"""Reject ambiguous workflows and mutable generated action references."""

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location(
    "workflow_contracts", ROOT / "scripts/workflow_contracts.py"
)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("Cannot load workflow contract checks")
CONTRACTS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(CONTRACTS)
SHA = "a" * 40
MARKER = "# Generated by venus-os-ci-toolkit/scripts/install_release.py; edit .release-policy.json.\n"


class WorkflowYAMLTests(unittest.TestCase):
    """Exercise real parsing and the generator/consumer boundary."""

    def test_duplicate_top_level_and_nested_keys_are_rejected(self):
        for source in (
            "jobs: {}\njobs: {}",
            "jobs:\n  test:\n    uses: one\n    uses: two",
        ):
            with self.subTest(source=source), self.assertRaises(ValueError):
                yaml.load(source, Loader=CONTRACTS.UniqueKeyLoader)

    def test_yaml_trigger_keys_and_scalars_remain_strings(self):
        result = yaml.load("on: push\nvalue: true\n", Loader=CONTRACTS.UniqueKeyLoader)
        self.assertEqual(result, {"on": "push", "value": "true"})

    def test_non_string_mapping_keys_are_rejected(self):
        with self.assertRaises(ValueError):
            yaml.load("? [one, two]\n: value", Loader=CONTRACTS.UniqueKeyLoader)

    def test_mutable_or_unknown_generated_actions_are_rejected(self):
        for reference, pins in (
            ("actions/checkout@main", None),
            ("actions/checkout@" + SHA, {}),
        ):
            workflow = {"jobs": {"build": {"steps": [{"uses": reference}]}}}
            with self.subTest(reference=reference), self.assertRaises(ValueError):
                CONTRACTS.validate_workflow_pins("quality-gate.yml", workflow, pins)

    def test_local_steps_and_matching_manifest_are_supported(self):
        workflow = {
            "jobs": {
                "build": {
                    "steps": [
                        {"run": "true"},
                        {"uses": "./local"},
                        {"uses": "actions/checkout@" + SHA},
                    ]
                }
            }
        }
        CONTRACTS.validate_workflow_pins(
            "quality-gate.yml", workflow, {"actions/checkout": SHA}
        )

    def test_consumers_without_manifest_still_require_sha_and_marker(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            folder = root / ".github/workflows"
            folder.mkdir(parents=True)
            path = folder / "quality-gate.yml"
            workflow = {
                "jobs": {"build": {"steps": [{"uses": "actions/checkout@" + SHA}]}}
            }
            path.write_text(MARKER)
            CONTRACTS.validate_generator_pins(root, {path.name: workflow})
            path.write_text("# marker removed\n")
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {path.name: workflow})
            path.write_text(MARKER)
            workflow["jobs"]["build"]["steps"][0]["uses"] = "actions/checkout@main"
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {path.name: workflow})

    def test_canonical_generator_requires_its_manifest(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "scripts").mkdir()
            (root / "scripts/install_release.py").touch()
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {})

    def test_manifest_mismatch_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            folder = root / ".github/workflows"
            folder.mkdir(parents=True)
            (folder / "quality-gate.yml").write_text(MARKER)
            (root / ".github/action-pins.json").write_text(
                json.dumps([{"packageName": "actions/checkout", "digest": "b" * 40}])
            )
            workflow = {
                "jobs": {"build": {"steps": [{"uses": "actions/checkout@" + SHA}]}}
            }
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"quality-gate.yml": workflow})

    def test_reusable_workflows_require_immutable_matching_references(self):
        action = "owner/repo/.github/workflows/build.yml"
        for reference, pins in (
            (action + "@main", None),
            (action + "@v1", None),
            (action + "@" + SHA, {}),
            (action + "@" + SHA, {action: "b" * 40}),
        ):
            workflow = {"jobs": {"build": {"uses": reference}}}
            with (
                self.subTest(reference=reference, pins=pins),
                self.assertRaises(ValueError),
            ):
                CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, pins)
        workflow = {"jobs": {"build": {"uses": action + "@" + SHA}}}
        CONTRACTS.validate_workflow_pins(
            "release-pipeline.yml", workflow, {action: SHA}
        )
        CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, None)
        workflow["jobs"]["build"]["uses"] = "./.github/workflows/build.yml"
        CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, {})

    def test_non_generated_workflows_require_sha_without_manifest_membership(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / ".github").mkdir()
            (root / ".github/action-pins.json").write_text(
                json.dumps([{"packageName": "actions/checkout", "digest": SHA}])
            )
            workflow = {"jobs": {"build": {"steps": [{"uses": "owner/action@" + SHA}]}}}
            CONTRACTS.validate_generator_pins(root, {"ci.yml": workflow})
            workflow["jobs"]["build"]["steps"][0]["uses"] = "owner/action@main"
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"ci.yml": workflow})
            workflow = {
                "jobs": {
                    "build": {"uses": "owner/repo/.github/workflows/build.yml@main"}
                }
            }
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"other.yml": workflow})


if __name__ == "__main__":
    unittest.main()


class CoverageProducerIdentityTests(unittest.TestCase):
    def setUp(self):
        self.ref = "a" * 40
        self.report = {"name": "runtime", "path": "coverage.xml", "format": "cobertura"}
        self.artifact = "coverage-runtime"

    def test_shared_language_producers_match_the_complete_identity(self):
        for format_name, workflow in (
            ("cobertura", "python-ci.yml"),
            ("go", "go-ci.yml"),
        ):
            with self.subTest(format=format_name):
                report = {**self.report, "format": format_name}
                producer = {
                    "uses": f"victron-venus/venus-os-ci-toolkit/.github/workflows/{workflow}@{self.ref}",
                    "with": {"coverage-artifact-name": self.artifact},
                }
                CONTRACTS.validate_coverage_producer(producer, report, self.ref)

    def test_reusable_non_producers_cannot_reuse_an_approved_commit(self):
        references = (
            f"untrusted/toolkit/.github/workflows/python-ci.yml@{self.ref}",
            f"victron-venus/venus-os-ci-toolkit/.github/workflows/coverage-upload.yml@{self.ref}",
            f"victron-venus/venus-os-ci-toolkit/.github/workflows/go-ci.yml@{self.ref}",
            "victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@"
            + "b" * 40,
            f"./.github/workflows/python-ci.yml@{self.ref}",
        )
        for reference in references:
            producer = {
                "uses": reference,
                "with": {"coverage-artifact-name": self.artifact},
            }
            with (
                self.subTest(reference=reference),
                self.assertRaisesRegex(ValueError, "producer pin"),
            ):
                CONTRACTS.validate_coverage_producer(producer, self.report, self.ref)

    def test_custom_export_requires_the_upload_action_and_immutable_pin(self):
        step = {
            "id": "export_coverage_runtime",
            "uses": "actions/upload-artifact@" + "b" * 40,
            "with": {
                "name": self.artifact + "-${{ github.run_attempt }}",
                "path": "coverage.xml",
            },
        }
        CONTRACTS.validate_coverage_producer({"steps": [step]}, self.report, self.ref)
        for reference in (
            None,
            "actions/download-artifact@" + "b" * 40,
            "untrusted/upload-artifact@" + "b" * 40,
            "actions/upload-artifact@v4",
            "actions/upload-artifact@" + "b" * 39,
            "actions/upload-artifact@" + "b" * 40 + "suffix",
        ):
            changed = (
                {**step, "uses": reference}
                if reference is not None
                else {key: value for key, value in step.items() if key != "uses"}
            )
            with (
                self.subTest(reference=reference),
                self.assertRaisesRegex(ValueError, "producer export"),
            ):
                CONTRACTS.validate_coverage_producer(
                    {"steps": [changed]}, self.report, self.ref
                )

    def test_lcov_has_no_shared_language_producer(self):
        producer = {
            "uses": f"victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@{self.ref}",
            "with": {"coverage-artifact-name": self.artifact},
        }
        report = {**self.report, "format": "lcov"}
        with self.assertRaisesRegex(ValueError, "producer pin"):
            CONTRACTS.validate_coverage_producer(producer, report, self.ref)
