apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: observability-backups-nfs-v1
  namespace: observability
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-synology-v4
  resources:
    requests:
      storage: 20Gi
